### ISSUE TITLE
set default value 

### ISSUE THREAD

**Issue by DavidHasan27** [maxkordiyak/react-native-dropdown-autocomplete#16]
How i can set default value for text input without focus, i want to show by default current location address when enter in screen, but i didnt see any props to set default value for text input.

**Comment by PaitoAnderson** [comment]
I've noticed this as well, I'll look at adding an `initialValue` prop for this.

**Comment by DavidHasan27** [comment]
Thanks @PaitoAnderson ,  One more thing,  Here we don't have option to select  'keyboardType', i think you should think about this

**Comment by PaitoAnderson** [comment]
@DavidHasan27 Added `keyboardType` the next update.

**Comment by ynirmal2** [comment]
initialValue props not working

**Comment by Skardaok** [comment]
been trying to add initial value, but either way : ( string (id) or object: {id: ****} do not work
