### ISSUE TITLE
scrollToInput is not a function

### ISSUE THREAD

**Issue by pixsolution** [maxkordiyak/react-native-dropdown-autocomplete#19]
Hello,

I am using your package, but it is giving me the following error when I clicked on the input field attached capture:
![Captura de Pantalla 2019-08-16 a la(s) 4 52 18 p  m](https://user-images.githubusercontent.com/47191848/63210277-8bb1a200-c0ec-11e9-83ca-d2903a85a6d0.png)

so the error indicates is by this line of code:
![Captura de Pantalla 2019-08-16 a la(s) 4 55 47 p  m](https://user-images.githubusercontent.com/47191848/63210307-d59a8800-c0ec-11e9-892d-e3be610e6341.png)
scrollToInput: Focus on selected field  
What other method can I use to write in the input field? because as you can see when I click on that field it gives the error

I appreciate your help
regards

**Comment by PaitoAnderson** [comment]
scrollToInput is a required input right now, just do something like `scrollToInput={ev => {}}` to satisfy this error. I'll look at making it a optional property in the future.

**Comment by pixsolution** [comment]
it work thanks!
