### ISSUE TITLE
[question] Is it possible to use with fixed content

### ISSUE THREAD

**Issue by Xyzor** [maxkordiyak/react-native-dropdown-autocomplete#2]
I'd like to use the module with a fixed array, without calling any api.

Is it possible?

**Comment by maxkordiyak** [comment]
@Xyzor Hi thanks for your message! I will update the library with ability to add a fixed array of items shortly.

**Comment by maxkordiyak** [comment]
@Xyzor you can now define a fixed array of items like this
```
const data = [
  "Apples",
  "Broccoli",
  "Chicken",
  "Duck",
  "Eggs",
  "Fish",
  "Granola",
  "Hash Browns",
];
```

then change your valueExtractor and pass the data to Autocomplete without fetchDataUrl
`<Autocomplete data={data} valueExtactor={item => item} />`

**Comment by Xyzor** [comment]
Awesome.

I'll leave this open for README update.
