### ISSUE TITLE
Pass the state of the autocomplete field to API

### ISSUE THREAD

**Issue by pixsolution** [maxkordiyak/react-native-dropdown-autocomplete#21]
Hello,
I need to consume an api and pass the state of the autocomplete field, that is, this is my api `https://www.mydomain.com/api/searchuserL?email=` after the = it should receive the letters that I write in the autocomplete field eg. `https://www.mydomain.com/api/searchuserL?email=searchterm`
Is it possible to do it with this library? I try using the `onChangeText = {(text) => this.setState ({text})}` to save the value and pass it to the api but when I use it it simply does not allow writing in autocomplete field? 
![Captura de Pantalla 2019-08-19 a la(s) 4 43 55 p  m](https://user-images.githubusercontent.com/47191848/63299889-25d53e00-c2d7-11e9-8ff8-587710222ded.png)

Is there any way I can make this requirement?

Regards

**Comment by PaitoAnderson** [comment]
Totally possible, just use the `fetchData` prop.

Example code:
```jsx
fetchData={async (searchTerm: string) => {
    return await search(searchTerm);
}}
```

**Comment by pixsolution** [comment]
Hi @PaitoAnderson  thanks for your reply

I tried that as you indicated but it keeps searching/loading the field and does nothing. Below attached code

```
fetchDataautocompletado = async (searchTerm) => {
  const response = await fetch(
 https://www.mydomain.com/api/searchuserL?emaill=${searchTerm}
);
  const autoc = await response.json();
  this.setState({ autocompletado: autoc });
  //};
  (componentDidMount() {
  this.fetchDataautocompletado();
  
  // In the autocomplete I added this field: 
  
   <Autocomplete
         defaultValue={searchTerm}
```

**Comment by PaitoAnderson** [comment]
So it would be more like this:
```jsx
<Autocomplete
    fetchData={async (searchTerm) => {
        const response = await fetch("https://www.mydomain.com/api/searchuserL?emaill=${searchTerm}");
        return await response.json();
    }}
/>
```

**Comment by pixsolution** [comment]
Thank you! Now changing it as you say gives me the following error:
![Captura de Pantalla 2019-08-20 a la(s) 3 03 06 p  m](https://user-images.githubusercontent.com/47191848/63376898-26c9a680-c38f-11e9-99f7-9809d29f5c05.png)

It is because the way you say it would remove state `//data={this.state.autocompletado}` then the code:

```Javascript
<Autocomplete
                  key={shortid.generate()}
                  style={baseStyles.input}
                  scrollToInput={ev => { }}
                  handleSelectItem={(item, id) => this.handleSelectItem(item, id)}
                  onDropdownClose={() => { }}
                  onDropdownShow={() => { }}
                  //data={this.state.autocompletado}
                  minimumCharactersCount={1}
                  defaultValue={searchTerm}
                  //onChangeText={(text) => this.setState({ text })}
                  highlightText
                  valueExtractor={item => item.email}
                  rightContent
                    rightTextExtractor={item => item.properties}
                    fetchData={async (searchTerm) => {
                     const response = await fetch(`https://www.mydomain.com/api/searchuserL?email=${searchTerm}`);
                    return await response.json();
                    }}
                  />
```

How do I send in this way what the user writes because the searchTerm is no longer defined?

**Comment by PaitoAnderson** [comment]
If the error is on load I would just delete this line ` defaultValue={searchTerm}`.

**Comment by pixsolution** [comment]
Thanks a lot it work :)

Last question, how can I change the placeholder?
![Captura de Pantalla 2019-08-20 a la(s) 4 01 08 p  m](https://user-images.githubusercontent.com/47191848/63380554-187f8880-c397-11e9-9f21-69970c70a94e.png)

**Comment by PaitoAnderson** [comment]
```js
placeholder="Whatever"
```
