### ISSUE TITLE
Style can't change

### ISSUE THREAD

**Issue by kaleb07** [maxkordiyak/react-native-dropdown-autocomplete#22]
Hi, i want to change style of dropdown autocomplete. But it's still same like default. Do you know what's wrong?

**Comment by PaitoAnderson** [comment]
Can you share an example of what you are trying?

There are quite a few properties available for styling:
https://github.com/maxkordiyak/react-native-dropdown-autocomplete#properties

**Comment by kaleb07** [comment]
<Autocomplete
              style={styles.inputBox3}
              scrollToInput={ev => {}}
              handleSelectItem={(item, id) => this.handleSelectItem(item, id)}
              onDropdownClose={() => {}}
              onDropdownShow={() => {}}
              data={projects}
              minimumCharactersCount={1}
              highlightText
              valueExtractor={item => item.title }
              rightContent
              rightTextExtractor={item => item.author}
              placeholder="Pilih proyek"
            />

const styles = StyleSheet.create({
inputBox3:{
    width: wp(90),
    height: hp(6),
    borderRadius:5,
    borderWidth: 0.5,
    borderColor: '#000000',
    backgroundColor: '#F5F5F5',
    fontSize:16,
    color:'#000000',
    marginVertical: 5,
  }
});

I'm using responsive screen in my style

**Comment by PaitoAnderson** [comment]
I see, instead of `style={styles.inputBox3}` try some of the other style properties we have like `inputStyle={styles.inputBox3}`.

Full list:
<img width="550" alt="Screen Shot 2019-08-20 at 11 44 37 AM" src="https://user-images.githubusercontent.com/4108718/63362571-0f170180-c340-11e9-8753-0d8c1ea6e89e.png">

**Comment by kaleb07** [comment]
It's working!! But, I don't want to use renderIcon. When i deleted renderIcon, the place of that icon is not deleted. The text is still next to icon place
![WhatsApp Image 2019-08-20 at 23 29 27](https://user-images.githubusercontent.com/45846170/63366072-22a78400-c3a3-11e9-8f9a-da47a46000cf.jpeg)
.

**Comment by PaitoAnderson** [comment]
Try:
```
inputStyle={{ paddingLeft: 10 }}
```

**Comment by PaitoAnderson** [comment]
```js
placeholder="Whatever"
```

**Comment by ghost** [comment]
you know I'm trying to find the right styles for the last 2 hours. They really need clear explanation or examples.
