### ISSUE TITLE
Mixed used of ref callback and React.createRef

### ISSUE THREAD

**Issue by Xyzor** [maxkordiyak/react-native-dropdown-autocomplete#3]
I'm playing with the master branch and it looks like the this.dropdown parameter is always null.

Also it gets value 2 times, once in the constructor `this.dropdown = React.createRef();` and once in the <Dropdown> ref callback:

```javascript
ref={ref => { this.dropdown = ref; }}
```

Is that intentional?

**Comment by maxkordiyak** [comment]
it looks like it is not intentional, I'll investigate this. in a meantime, if you have any suggestions please go ahead

**Comment by Xyzor** [comment]
The cause of null dropdown is probably my bad.  
I just found out the provided content is an empty array.
