### ISSUE TITLE
Possibility to reset the input in handleSelectItem

### ISSUE THREAD

**Issue by CyNn0** [maxkordiyak/react-native-dropdown-autocomplete#7]
Hello there, is it possible to reset the input in handleSelectItem.
if we want to choose multiple item from the same dropdown, we have to erase it manually and each time it triggers the search,

**Comment by maxkordiyak** [comment]
Hello, if you please add this feature and open a PR? I’m now unavailable to maintain this package.

**Comment by CyNn0** [comment]
i might do that on my free time

**Comment by CyNn0** [comment]
Thx for your reactivity i'm closing the issue
