### ISSUE TITLE
Problem in RN 0.60.4

### ISSUE THREAD

**Issue by vre142** [maxkordiyak/react-native-dropdown-autocomplete#9]
Hi, When I want to use your library in RN 0.60.4 show me error that listview has been removed from react native. what can I do now?
Thanks

**Comment by PaitoAnderson** [comment]
@vre142 This should be resolved with `1.0.12`.

**Comment by PaitoAnderson** [comment]
@vre142 I realize now it's not deployed yet, sorry, I'm new to this project. Check for it in the next update or test with `maxkordiyak/react-native-dropdown-autocomplete`. Thanks!

**Comment by okechukwu0127** [comment]
Hallo.
I ran into an error while trying to use ur great package on my application.
My react-native version is  RN.60.4 as well.

I have a feeling its not linking properly as i dont seem to see it been imported  in my **MainApplication.java**  file.

I also tried manual linking command using **react-native link react-native-dropdown-autocomplete** but nothing happened.

Kindly tell me what i am not doing fine. Or is the package not compatible with RN. 0.60.4 ? 


Find the error message i get on the attached image.

![Screenshot_20190805-222437](https://user-images.githubusercontent.com/23473673/62496276-53e35a00-b7d0-11e9-99b3-77a79dc231e4.jpg)

**Comment by PaitoAnderson** [comment]
@okechukwu0127 You don't need to link this package at all, as it's pure javascript :)

I tested in RN 0.60.4 just now seems to work fine for me.

**Comment by okechukwu0127** [comment]
so why is it not working for me ?

**Here is a link to my main component codes**
https://codeshare.io/G86XeJ

Everything seems fine but i keep getting the same error over and over.

I can share any other code if need be.

Can someone tell me what i am not doing right please ?

**Comment by okechukwu0127** [comment]
> @okechukwu0127 You don't need to link this package at all, as it's pure javascript :)
> 
> I tested in RN 0.60.4 just now seems to work fine for me.

Thats really strenge. 
Its not working for me at all.

**Comment by PaitoAnderson** [comment]
@okechukwu0127 I'm sorry, I looked at your code to nothing obviously wrong.

**Comment by arpitprod** [comment]
@okechukwu0127  you didn't add HOC `withKeyboardAwareScrollView` in your class `IndexEmail`. So, export your class like this

> export default withKeyboardAwareScrollView(IndexEmail);
